[package]
name = "afire_tls"
version = "0.1.0"
edition = "2021"

[dependencies]
afire = { git = "https://github.com/Basicprogrammer10/afire.git", branch = "dev" }
rustls = "0.22.1"
rustls-pemfile = "2.0.0"
